import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${nunito_sans.className} mt-10 max-tablet:mt-[20px] antialiased`}
      >
        <div className="flex flex-col items-center">
          <div className="grid grid-cols-[193px_minmax(0,1fr)] max-w-[1348px] max-tablet:flex">
            <Sidebar className="max-tablet:hidden" />
            <div className="flex flex-col ml-8 laptop:max-w-[1120px] max-laptop:max-w-185.5 max-tablet:ml-0 max-mobile:max-w-[90vw] min-w-[340px]">
              <div className="flex items-center w-full">
                <Sidebar className="mr-[20px] tablet:hidden" />
                {/* <Burger /> */}
                <Header />
              </div>
              <main className="">{children}</main>
            </div>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
